package jry;

import java.util.Random;
import java.util.Scanner;

public class RandomNumber {
    public static void main(String[] args) {
        Random r = new Random();
        Scanner sc = new Scanner(System.in);
        boolean lang = true;
        System.out.println("Please choose your language:");
        System.out.println("请选择你的语言：");
        System.out.println("1.简体中文 2.English");
        while(true) {
            int language = sc.nextInt();
            if (language == 1) {
                lang = true;
                System.out.println("语言已被设置为简体中文！");
                break;
            } else if (language == 2) {
                lang = false;
                System.out.println("The language is English now!");
                break;
            } else {
                System.out.println("Input error, please re-enter:");
                System.out.println("输入有误，请重新输入：");
            }
        }
        if(lang){
            while (true) {
                int Number = r.nextInt(100) + 1;
                int score = 100;
                System.out.println("来丸个游戏吧");
                System.out.println("猜猜系统随机生成的随机数字(1~100)");
                while (true) {
                    int a = sc.nextInt();
                    if (a == Number) {
                        System.out.println("猜中了");
                        System.out.println("你得了" + score + "分哦");
                        break;
                    } else if (a > Number) {
                        score -= 10;
                        if (score > 0) {
                            System.out.println("猜大了");
                            System.out.println("再来一次吧！");
                        }
                        if (score == 0) {
                            System.out.println("你已猜错10次");
                            System.out.println("猜数机会已用尽");
                            System.out.println("你得了0分哦");
                            break;
                        }
                    } else {
                        score -= 10;
                        if (score > 0) {
                            System.out.println("猜小了");
                            System.out.println("再来一次吧！");
                        }
                        if (score == 0) {
                            System.out.println("你已猜错10次");
                            System.out.println("猜数机会已用尽");
                            System.out.println("你得了0分哦");
                            break;
                        }
                    }
                }
                System.out.println("请选择重来或退出游戏(输入Y为重来，输入N为退出)");
                String choice = sc.next();
                while (true) {
                    if (choice.equals("Y") || choice.equals("y") || choice.equals("N") || choice.equals("n")) {
                        break;
                    } else {
                        System.out.println("输入有误，请重新输入：");
                        choice = sc.next();
                    }
                }
                if (choice.equals("N") || choice.equals("n")) {
                    System.out.println("游戏结束！");
                    break;
                }
            }
        }
        if(!lang){
            while(true) {
                int Number = r.nextInt(100) + 1;
                int score = 100;
                System.out.println("Let's play a game");
                System.out.println("Guess the number randomly generated by the system(1~100)");
                while (true) {
                    int a = sc.nextInt();
                    if (a == Number) {
                        System.out.println("Bingo!");
                        System.out.println("Your score is: " + score );
                        break;
                    } else if (a > Number) {
                        score -= 10;
                        if (score > 0) {
                            System.out.println("It's larger than the right number");
                            System.out.println("Try again!");
                        }
                        if (score == 0) {
                            System.out.println("You've guessed wrong ten times");
                            System.out.println("You don't have any chance");
                            System.out.println("Your score is : 0");
                            break;
                        }
                    } else {
                        score -= 10;
                        if (score > 0) {
                            System.out.println("It's smaller than the right number");
                            System.out.println("Try again!");
                        }
                        if (score == 0) {
                            System.out.println("You've guessed wrong ten times");
                            System.out.println("You don't have any chance");
                            System.out.println("Your score is : 0");
                            break;
                        }
                    }
                }
                System.out.println("Please choose to restart or exit the game(Press Y for restart and N for exit)");
                String choice = sc.next();
                while (true) {
                    if (choice.equals("Y") || choice.equals("y") || choice.equals("N") || choice.equals("n")) {
                        break;
                    } else {
                        System.out.println("Input error, please re-enter:");
                        choice = sc.next();
                    }
                }
                if (choice.equals("N") || choice.equals("n")) {
                    System.out.println("Game over!");
                    break;
                }
            }
        }
    }
}